### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by andyyuan78** [alexkaiser/mc_stretch#1]
ubgpu@ubgpu:~/github/mc_stretch$ 
ubgpu@ubgpu:~/github/mc_stretch$ make
gcc -c -Wall -O3 -std=gnu99  stretch_move_main.c
In file included from stretch_move_sampler.h:35:0,
                 from stretch_move_main.c:34:
cl-helper.h:36:19: fatal error: CL/cl.h: No such file or directory
 #include <CL/cl.h>
                   ^
compilation terminated.
make: **\* [stretch_move_main.o] Error 1
ubgpu@ubgpu:~/github/mc_stretch$

**Comment by alexkaiser** [comment]
Do you have opencl installed on this system? How do you normally link to it? Do other opencl programs work correctly?

**Comment by yaanlpc** [comment]
I have similar situation like this, but it's not for this program. I tried dartable -d opencl, it works pretty well and also clinfo gave positive info, so Ipresume my opencl is installed with CUDA and display driver together, but I still get warning, cl-helper.h:36:19: fatal error: CL/cl.h: No such file or directory. 

I suspect it's nvidia opencl is not versatile, do I have to install another one, I am concerned it will wipe out my nvidia openCL which is the basis for some of my software.

**Comment by alexkaiser** [comment]
I'm not sure I follow the details. What is dartable?

Can you compile a basic opencl program from source, and if so how would you
do so? Do you have that header on your machine and within your path?

**Comment by yaanlpc** [comment]
My issue has been resolved by creating a soft link in /usr/include for CL to opencl library. looks like CUDA forgot to create that one after the installation of openCL.
